name: tdd_courses_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI icons for Cupertino style
  cupertino_icons: ^1.0.2

  # State management library
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Simplifies equality comparisons
  equatable: ^2.0.5

  # Functional programming in Dart
  dartz: ^0.10.1

  # File picker for selecting files
  file_picker: ^5.5.0

  # Icons library
  iconly: ^1.0.1

  # Image picker for selecting images
  image_picker: ^1.0.4

  # Internationalization and localization
  intl: ^0.18.1

  # Lottie animations
  lottie: ^2.6.0

  # Opening files
  open_file: ^3.3.2

  # File system access
  path_provider: ^2.1.1

  # State management library
  provider: ^6.0.5

  # Persistent local storage
  shared_preferences: ^2.2.1

  # Page indicator widget
  smooth_page_indicator: ^1.1.0

  # Swipe gestures
  swipe_to: ^1.0.2

  # URL launcher for opening external links
  url_launcher: ^6.1.14

  # Metadata for YouTube videos
  youtube_metadata: ^1.0.1

  # Generating video thumbnails
  video_thumbnail: ^0.5.3

  # Video player widget
  chewie: ^1.7.1

  # FontAwesome icons
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  # Flutter testing framework
  flutter_test:
    sdk: flutter

  # Linting for Flutter projects
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
