name: tdd_courses_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  # Flutter core
  flutter:
    sdk: flutter

  # UI components
  cupertino_icons: ^1.0.2
  iconly: ^1.0.1
  font_awesome_flutter: ^10.5.0
  gap: ^3.0.1

  # State management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  get_it: ^7.6.4

  # Functional programming
  equatable: ^2.0.5
  dartz: ^0.10.1

  # File handling
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  open_file: ^3.3.2
  path_provider: ^2.1.1

  # Internationalization
  intl: ^0.18.1

  # Animation and visualization
  lottie: ^2.6.0
  smooth_page_indicator: ^1.1.0

  # Swipe gestures
  swipe_to: ^1.0.2

  # URL handling
  url_launcher: ^6.1.14

  # Metadata and video handling
  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3
  chewie: ^1.7.1

  # Firebase and authentication
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  firebase_core: ^2.15.1
  firebase_ui_auth: ^1.7.0

  # Local storage
  shared_preferences: ^2.2.1
  uuid: ^3.0.7

dev_dependencies:
  # Flutter testing
  flutter_test:
    sdk: flutter

  # Linting and analysis
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0

  # Testing utilities
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

  # Firebase mocking
  firebase_auth_mocks: ^0.12.0
  google_sign_in_mocks: ^0.3.0
  fake_cloud_firestore: ^2.4.1+1
  firebase_storage_mocks: ^0.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
