name: tdd_courses_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI icons for Cupertino style
  cupertino_icons: ^1.0.2

  # State management library
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Simplifies equality comparisons
  equatable: ^2.0.5

  # Functional programming in Dart
  dartz: ^0.10.1

  # File picker for selecting files
  file_picker: ^5.5.0

  # Icons library
  iconly: ^1.0.1

  # Image picker for selecting images
  image_picker: ^1.0.4

  # Internationalization and localization
  intl: ^0.18.1

  # Lottie animations
  lottie: ^2.6.0

  # Opening files
  open_file: ^3.3.2

  # File system access
  path_provider: ^2.1.1

  # State management library
  provider: ^6.0.5

  # Persistent local storage
  shared_preferences: ^2.2.1

  # Page indicator widget
  smooth_page_indicator: ^1.1.0

  # Swipe gestures
  swipe_to: ^1.0.2

  # URL launcher for opening external links
  url_launcher: ^6.1.14

  # Metadata for YouTube videos
  youtube_metadata: ^1.0.1

  # Generating video thumbnails
  video_thumbnail: ^0.5.3

  # Video player widget
  chewie: ^1.7.1

  # FontAwesome icons
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.4
  gap: ^3.0.1

dev_dependencies:
  # Flutter testing framework
  flutter_test:
    sdk: flutter

  # Linting for Flutter projects
  flutter_lints: ^2.0.0

  # Testing utilities for BLoC
  bloc_test: ^9.1.4

  # Mocking library for testing
  mocktail: ^1.0.0

  # Static analysis tool for Dart & Flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
